### ISSUE TITLE
Port to WebExtensions API

### ISSUE THREAD

**Issue by francov** [RealFatCat/hot-translate#6]
Hi,
I've ported this extension to use the new [WebExtensions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions). So It now supports multiprocess too.
Can I make a pull request with the modifications? Ah, for testing purposes I used your Yandex Api key, that i will not publish.

Let me know if i can proceed with the pull request.

**Comment by francov** [comment]
It will solve the issue #3 too

**Comment by RealFatCat** [comment]
Sure, why not, send the PR.
